import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
chars = "\u00141"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00142"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00143"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00144"
key = "Key4"
mods = "Control"

[window]
opacity = 0.9

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
