#!/bin/zsh
if [[ -z $STOW_FOLDERS ]]; then
   STOW_FOLDERS="nvim-kickstart,zsh,tmux,personal,bin,oh-my-zsh,alacritty,ssh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/projects/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
