#!/usr/bin/bash
if [[ -z $STOW_FOLDERS ]]; then
   STOW_FOLDERS="bin,bash,nvim-kickstart,tmux,wezterm"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/ws/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
