#!/usr/bin/zsh
if [[ -z $STOW_FOLDERS ]]; then
   STOW_FOLDERS="nvim-kickstart,tmux"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/ws/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
