#!/usr/bin/zsh
if [[ -z $STOW_FOLDERS ]]; then
   STOW_FOLDERS="nvim,zsh,tmux,personal,bin,i3,i3status,awesome"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/projects/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
